# Generated by Django 5.2.15 on 2026-08-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='library.sample')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('sample',), name='unique_current_variant_per_sample')],
            },
        ),
    ]
