# Generated by Django 5.2.15 on 2026-08-12 21:48

import django.db.models.deletion
import django.utils.timezone
import processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedvariant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.variant_upload_path),
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='operation',
            field=models.CharField(choices=[('eq', 'Equalisation'), ('normalise', 'Normalise'), ('trim', 'Trim silence'), ('denoise', 'De-noise')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='peaks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='source_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_variants', to='processing.processedvariant'),
        ),
        migrations.AddField(
            model_name='processedvariant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
