# Generated by Django 5.2.15 on 2026-08-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_processedvariant_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedVariant',
        ),
    ]
