# Generated by Django 5.2.15 on 2026-08-03 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('bpm_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('tonic', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('mode', models.CharField(blank=True, choices=[('major', 'Major'), ('minor', 'Minor')], max_length=10)),
                ('key_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('instrument', models.CharField(blank=True, max_length=50)),
                ('quality_flags', models.JSONField(blank=True, default=dict)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline_version', models.CharField(blank=True, max_length=20)),
                ('bpm_override', models.FloatField(blank=True, null=True)),
                ('tonic_override', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('mode_override', models.CharField(blank=True, choices=[('major', 'Major'), ('minor', 'Minor')], max_length=10)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'derived metadata',
            },
        ),
    ]
