# Generated by Django 5.2.15 on 2026-08-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedmetadata',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='library.sample'),
        ),
        migrations.AddIndex(
            model_name='derivedmetadata',
            index=models.Index(fields=['bpm'], name='analysis_de_bpm_40a3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='derivedmetadata',
            index=models.Index(fields=['tonic', 'mode'], name='analysis_de_tonic_e8aad3_idx'),
        ),
        migrations.AddIndex(
            model_name='derivedmetadata',
            index=models.Index(fields=['analysed_at'], name='analysis_de_analyse_d68a75_idx'),
        ),
        migrations.AddConstraint(
            model_name='derivedmetadata',
            constraint=models.CheckConstraint(condition=models.Q(('tonic__isnull', True), ('tonic__range', (0, 11)), _connector='OR'), name='tonic_in_pitch_class_range'),
        ),
        migrations.AddConstraint(
            model_name='derivedmetadata',
            constraint=models.CheckConstraint(condition=models.Q(('tonic_override__isnull', True), ('tonic_override__range', (0, 11)), _connector='OR'), name='tonic_override_in_pitch_class_range'),
        ),
        migrations.AddConstraint(
            model_name='derivedmetadata',
            constraint=models.CheckConstraint(condition=models.Q(('bpm__isnull', True), ('bpm__gt', 0), _connector='OR'), name='bpm_positive'),
        ),
        migrations.AddConstraint(
            model_name='derivedmetadata',
            constraint=models.CheckConstraint(condition=models.Q(('bpm_override__isnull', True), ('bpm_override__gt', 0), _connector='OR'), name='bpm_override_positive'),
        ),
    ]
