# Generated by Django 5.2.15 on 2026-08-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedmetadata',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='derivedmetadata',
            name='channels',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivedmetadata',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivedmetadata',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='derivedmetadata',
            name='instrument_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivedmetadata',
            name='peaks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='derivedmetadata',
            name='sample_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivedmetadata',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
