# Generated by Django 5.2.15 on 2026-09-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_derivedmetadata_attempts_derivedmetadata_channels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivedmetadata',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='derivedmetadata',
            name='instrument_confidence',
        ),
    ]
